from pathlib import Path

HOME = Path("artifacts/solana-multi-wallet/src/pages/home.tsx")
CSS = Path("artifacts/solana-multi-wallet/src/index.css")

def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f"Could not patch {label}: expected block not found")
    return text.replace(old, new, 1)

home = HOME.read_text()
home = replace_once(home, "const THEME_STORAGE_KEY = 'multi-wallet:theme:v1';\n", "const THEME_STORAGE_KEY = 'multi-wallet:theme:v1';\nconst TRADE_DRAFTS_STORAGE_KEY = 'multi-wallet:trade-drafts:v1';\n", 'trade drafts storage key')
home = replace_once(home, "  const [buyAmount, setBuyAmount] = useState('0.01');\n  const [sellPct, setSellPct] = useState('100');\n\n  const [tpPct, setTpPct] = useState('100');\n", "  const [buyAmount, setBuyAmount] = useState('0.01');\n  const [sellPct, setSellPct] = useState('100');\n\n  const [tradeDrafts, setTradeDrafts] = useState<\n    Record<string, { buyAmount: string; sellPct: string }>\n  >(() => {\n    try {\n      const saved = localStorage.getItem(TRADE_DRAFTS_STORAGE_KEY);\n      return saved ? JSON.parse(saved) : {};\n    } catch {\n      return {};\n    }\n  });\n\n  const [tpPct, setTpPct] = useState('100');\n", 'per-wallet trade state')
home = replace_once(home, '  useEffect(() => {\n    document.documentElement.dataset.theme = theme;\n    localStorage.setItem(THEME_STORAGE_KEY, theme);\n  }, [theme]);\n\n  useEffect(() => {\n', '  useEffect(() => {\n    document.documentElement.dataset.theme = theme;\n    localStorage.setItem(THEME_STORAGE_KEY, theme);\n  }, [theme]);\n\n  useEffect(() => {\n    localStorage.setItem(\n      TRADE_DRAFTS_STORAGE_KEY,\n      JSON.stringify(tradeDrafts),\n    );\n  }, [tradeDrafts]);\n\n  useEffect(() => {\n', 'persist per-wallet trade state')
home = replace_once(home, '  async function trade(\n', "  function changeTradeDraft(\n    address: string,\n    key: 'buyAmount' | 'sellPct',\n    value: string,\n  ) {\n    const cleaned = value.replace(/[^0-9.]/g, '');\n\n    setTradeDrafts((prev) => ({\n      ...prev,\n      [address]: {\n        buyAmount:\n          key === 'buyAmount'\n            ? cleaned\n            : prev[address]?.buyAmount ?? buyAmount,\n        sellPct:\n          key === 'sellPct'\n            ? cleaned\n            : prev[address]?.sellPct ?? sellPct,\n      },\n    }));\n  }\n\n  async function trade(\n", 'trade draft updater')
home = replace_once(home, "    setBusy(`${address}:${side}`);\n    setNotice('');\n\n    try {\n      const data = await api('/api/execution/trade', {\n        method: 'POST',\n        body: JSON.stringify({\n          address,\n          mint: mint.trim(),\n          side,\n          amountSol: Number(buyAmount),\n          sellPct: Number(sellPct),\n        }),\n      });\n", "    const walletTrade = tradeDrafts[address] || {\n      buyAmount,\n      sellPct,\n    };\n\n    const walletBuyAmount = Number(walletTrade.buyAmount);\n    const walletSellPct = Number(walletTrade.sellPct);\n\n    if (\n      side === 'buy' &&\n      (!Number.isFinite(walletBuyAmount) || walletBuyAmount <= 0)\n    ) {\n      setNotice(`Enter a valid BUY amount for ${short(address)}.`);\n      return;\n    }\n\n    if (\n      side === 'sell' &&\n      (\n        !Number.isFinite(walletSellPct) ||\n        walletSellPct <= 0 ||\n        walletSellPct > 100\n      )\n    ) {\n      setNotice(`SELL % for ${short(address)} must be 1–100.`);\n      return;\n    }\n\n    setBusy(`${address}:${side}`);\n    setNotice('');\n\n    try {\n      const data = await api('/api/execution/trade', {\n        method: 'POST',\n        body: JSON.stringify({\n          address,\n          mint: mint.trim(),\n          side,\n          amountSol: walletBuyAmount,\n          sellPct: walletSellPct,\n        }),\n      });\n", 'individual trade values')
home = replace_once(home, '              const draft =\n                drafts[wallet.address] || {\n                  tpPct,\n                  tpSellPct,\n                  slPct,\n                  slSellPct,\n                };\n\n              return (\n', '              const draft =\n                drafts[wallet.address] || {\n                  tpPct,\n                  tpSellPct,\n                  slPct,\n                  slSellPct,\n                };\n\n              const tradeDraft =\n                tradeDrafts[wallet.address] || {\n                  buyAmount,\n                  sellPct,\n                };\n\n              return (\n', 'wallet trade draft in render')
home = replace_once(home, '                  <div className="trade-row">\n                    <span>BUY</span>\n                    <button\n                      className="buy"\n                      onClick={() => trade(wallet.address, \'buy\')}\n                      disabled={Boolean(busy) || !wallet.enabled}\n                    >\n                      BUY\n                    </button>\n                    <span>SELL</span>\n                    <button\n                      className="sell"\n                      onClick={() => trade(wallet.address, \'sell\')}\n                      disabled={Boolean(busy) || !wallet.enabled}\n                    >\n                      SELL\n                    </button>\n                  </div>\n', '                  <div className="trade-row">\n                    <span>BUY</span>\n\n                    <div className="trade-value">\n                      <input\n                        inputMode="decimal"\n                        value={tradeDraft.buyAmount}\n                        onChange={(event) =>\n                          changeTradeDraft(\n                            wallet.address,\n                            \'buyAmount\',\n                            event.target.value,\n                          )\n                        }\n                        aria-label={`Buy amount for ${wallet.address}`}\n                      />\n                      <b>SOL</b>\n                    </div>\n\n                    <button\n                      className="buy"\n                      onClick={() => trade(wallet.address, \'buy\')}\n                      disabled={Boolean(busy) || !wallet.enabled}\n                    >\n                      BUY\n                    </button>\n\n                    <span>SELL</span>\n\n                    <div className="trade-value">\n                      <input\n                        inputMode="decimal"\n                        value={tradeDraft.sellPct}\n                        onChange={(event) =>\n                          changeTradeDraft(\n                            wallet.address,\n                            \'sellPct\',\n                            event.target.value,\n                          )\n                        }\n                        aria-label={`Sell percentage for ${wallet.address}`}\n                      />\n                      <b>%</b>\n                    </div>\n\n                    <button\n                      className="sell"\n                      onClick={() => trade(wallet.address, \'sell\')}\n                      disabled={Boolean(busy) || !wallet.enabled}\n                    >\n                      SELL\n                    </button>\n                  </div>\n', 'per-wallet buy/sell controls')
HOME.write_text(home)
css = CSS.read_text()
css += "\n\n/* v6.9 per-wallet trade amounts */\n.trade-row {\n  grid-template-columns:\n    auto minmax(62px, .95fr) minmax(46px, .72fr)\n    auto minmax(54px, .82fr) minmax(46px, .72fr);\n}\n\n.trade-value {\n  min-width:0;\n  display:grid;\n  grid-template-columns:minmax(0,1fr) auto;\n  gap:3px;\n  align-items:center;\n}\n\n.trade-value input {\n  width:100%;\n  height:28px;\n  padding:0 5px;\n  text-align:right;\n  font-size:10px;\n}\n\n.trade-value b {\n  font-size:7px;\n  font-weight:600;\n  color:#777;\n}\n\nhtml[data-theme='dark'] .trade-value b {\n  color:#8d8d8d;\n}\n\n@media (max-width: 390px) {\n  .trade-row {\n    gap:4px;\n    grid-template-columns:\n      auto minmax(58px, .95fr) minmax(43px, .70fr)\n      auto minmax(50px, .80fr) minmax(43px, .70fr);\n  }\n\n  .trade-value input {\n    padding:0 4px;\n    font-size:9px;\n  }\n}\n"
CSS.write_text(css)
print("v6.9 per-wallet BUY/SELL amounts applied.")
